### ISSUE TITLE
update to `safegraph_weekly_patterns` when there is no `date`

### ISSUE THREAD

**Issue by echong-SG** [echong-SG/API-python-client-MKilic#35]
Hey @mirkan1, we added a default date behavior to `safegraph_weekly_patterns` on the API side.  So, if a user does not specify a `date`, you can pass something like the below:

```
query {
  lookup(placekey: "222-224@5vg-7gr-6kz") { 
		placekey 
    safegraph_weekly_patterns {
      raw_visit_counts
    }
  }
}
```

Notice that the `safegraph_weekly_patterns` part does not include a `(date: "YYYY-MM-DD")` parameter. This will return the most recent weekly patterns by default now.

**Comment by mirkan1** [comment]
I will write it so they have to give date if they want data from weekly and/or monthly

**Comment by mirkan1** [comment]
https://github.com/echong-SG/API-python-client-MKilic/issues/45

**Comment by mirkan1** [comment]
you fixed this one right? you added something to types for this case
