### ISSUE TITLE
return error if a requested column is not in the selected `product`

### ISSUE THREAD

**Issue by echong-SG** [echong-SG/API-python-client-MKilic#36]
@mirkan1 This works, as expected:

```
cols = [
    'placekey',
    'location_name',
    'street_address',
]

sgql_client.lookup(
    product = 'core',
    placekeys = example_pk, 
    columns = cols
)
```

But this should return an error that says: `raw_visit_counts is not an available column in SafeGraph Core. Please select among: {list of all columns in Core}"

```
cols = [
    'placekey',
    'location_name',
    'street_address',
    'raw_visit_counts'
]

sgql_client.lookup(
    product = 'core',
    placekeys = example_pk, 
    columns = cols
)
```

**Comment by mirkan1** [comment]
https://github.com/echong-SG/API-python-client-MKilic/issues/36
please confirm the fix or enchance then close this issue :)
