### ISSUE TITLE
Every query should include `placekey` column 

### ISSUE THREAD

**Issue by echong-SG** [echong-SG/API-python-client-MKilic#37]
@mirkan1 We should include the `placekey` column by default in every query. Notice that this doesn't hit any endpoint like `safegraph_core` or `geometry`, it's just on its own.

Example below:

```
query {
  lookup(placekey: "222-224@5vg-7gr-6kz") { 
		placekey # <----- this
    safegraph_core {
      location_name
    }
    safegraph_weekly_patterns {
      raw_visit_counts
    }
  }
}
```

**Comment by echong-SG** [comment]
Really? Do you see the highlighted stuff in the return?

![image](https://user-images.githubusercontent.com/77634999/133719162-db6f71f3-731f-46b7-8314-f08cc52b5b6d.png)

**Comment by mirkan1** [comment]
https://github.com/echong-SG/API-python-client-MKilic/commit/22ca31515c45d310aba86e2a6660fd18e22b7024

**Comment by echong-SG** [comment]
Think I fixed this in: https://github.com/echong-SG/API-python-client-MKilic/commit/d5c5061cff1e968be65599f32dbcba94ba6e90b0
