### ISSUE TITLE
Do not return null rows for `weekly_patterns` or `monthly_patterns`

### ISSUE THREAD

**Issue by echong-SG** [echong-SG/API-python-client-MKilic#38]
@mirkan1 We do not always have `weekly_patterns` or `monthly_patterns` data for every placekey every week/month. In some cases, it's b/c we never have foot traffic data for that location b/c of the type of location, and in other cases, we have that data for some months, but not others.

In cases where we `weekly_patterns` or `monthly_patterns` is `null` for a given placekey+time period, we should not include that row in the output. 

In the example below, we should _not_ include the two null rows.
![image](https://user-images.githubusercontent.com/77634999/133348219-9c5a9e2b-7664-4875-a6a6-c2ea38cd4b30.png)

```
# placekey without many visits
sparse_pk = '228-222@63s-dvy-9cq' # Fu Wah Mini Market in Philadelphia

# array of dates
dates = [
    '2021-08-24', 
    '2020-08-25', 
    '2018-08-25'
]
cols = [
    'safegraph_core.*',
    'placekey',
    'location_name',
    'street_address',
    'city',
    'region',
    'brands',
    'date_range_start',
    'raw_visit_counts',
    'visits_by_day'
]

sgql_client.lookup(
    product = 'weekly_patterns',
    placekeys = sparse_pk, 
    date = dates,
    columns = cols,
    patterns_version = 'weekly'
)
```

**Comment by mirkan1** [comment]
https://github.com/echong-SG/API-python-client-MKilic/commit/22ca31515c45d310aba86e2a6660fd18e22b7024

**Comment by mirkan1** [comment]
can you also approve that this is fixed with a diffirent case?

**Comment by echong-SG** [comment]
@mirkan1 I think this one still needs fixing.

The second row should _**not**_ be returned by this code: 

```
cols = [
    'placekey',
    'location_name',
    'brands',
    'date_range_start',
    'raw_visit_counts',
    'visitor_home_cbgs'
]

sgql_client.lookup(
    product = 'weekly_patterns',
    placekeys = pks, 
    columns = cols,
    date = '2021-08-15'
)
```

![image](https://user-images.githubusercontent.com/77634999/134243684-676b90df-ebbd-4ddf-9d77-082445fa3ebe.png)


I think I broke something while making changes for this issue: https://github.com/echong-SG/API-python-client-MKilic/issues/41
