### ISSUE TITLE
Remove `patterns_version` argument

### ISSUE THREAD

**Issue by echong-SG** [echong-SG/API-python-client-MKilic#40]
@mirkan1 Now that we require the `product` argument, the `patterns_version` argument should be unnecessary, and we should remove it.

For example, in the below, we say `product = 'weekly_patterns'` and then require the user to also specify `patterns_version = 'weekly'`, which is redundant.

```
example_weekly_patterns = sgql_client.lookup(product = 'weekly_patterns', placekeys = example_pk, columns = '*', date = '2021-08-05', patterns_version = 'weekly')
```

**Comment by mirkan1** [comment]
I changed a major line.
pytest passed but I think you might want to test it as well
https://github.com/echong-SG/API-python-client-MKilic/commit/a350f6b361a6f0f54a50d6c1ffd64d3e80552c50#diff-bbe34bd5f41f00a48b348f62a944221d0b79ed9887359a144e6b747682983a10L209

**Comment by echong-SG** [comment]
looks good
