### ISSUE TITLE
do not cache `date` value when querying weekly_patterns

### ISSUE THREAD

**Issue by echong-SG** [echong-SG/API-python-client-MKilic#42]
@mirkan1 Currently, the client "remembers" the most recent date passed when querying Weekly Patterns.

It should reset the date to the default value.

![image](https://user-images.githubusercontent.com/77634999/133617316-af671921-72a2-4740-9e4a-fb804c97c397.png)

**Comment by mirkan1** [comment]
I wrote so date is a required field now if product is either weekly_patterns or monthly_patterns

**Comment by mirkan1** [comment]
oh nvm

**Comment by mirkan1** [comment]
you already fixed this issue
