### ISSUE TITLE
asking for ipdb> 

### ISSUE THREAD

**Issue by aghalandar** [echong-SG/API-python-client-MKilic#50]
Hi, 
When I run the following example by the documentation: 
brand = 'Sheetz'
region = 'PA'
max_results = 200

search_result = sgql_client.search(product = 'core', columns = '*', brand = brand, region = region, max_results = max_results)

here is the response:
> c:\users\aghal\appdata\roaming\python\python38\site-packages\safegraphql\client.py(693)search()
    691         import pdb;pdb.set_trace()
    692 
--> 693         self.__lengthCheck__(data_frame)
    694         self.__adjustments(data_frame)
    695         self.__error_check(after_result_number)

The code asks for:
 ipdb> [               ]

I am not sure what should I do. I have this problem with search with all the examples.

**Comment by echong-SG** [comment]
@aghalandar thanks very much for flagging this.

@mirkan1 looks like some debugging code was left in `search()`. can you remove that and confirm that the query pasted above works? Please also update on pypi when it's fixed. thank you.

**Comment by mirkan1** [comment]
sorry for that, sending working version in a second

**Comment by echong-SG** [comment]
no problem, thanks!
