### ISSUE TITLE
efficient way to send multiple request

### ISSUE THREAD

**Issue by aghalandar** [echong-SG/API-python-client-MKilic#51]
Hi again, 
I want to download a weekly pattern for a particular naics_code (school) over time. However, there are 126000 unique place keys for schools in the database. I write down a code to iterate one by one and send a request, but I got 

HTTPError: 429 Client Error: Too Many Requests... error

What is the efficient way to request a lookup without causing problems? I download the monthly data from the Safegraph shop but I guess sending too many requests would not be efficient. 
Thank you for the help.

**Comment by echong-SG** [comment]
Hey @aghalandar for getting multiple records from a single naics, the `search()` function would be the way to go. However, 126k is a lot of records, and the API's not at the point yet where it can handle requests of that size. We're working on it.

How much history do you need?

We created a temporary endpoint for bulk weekly_patterns downloads that'll let you get all Patterns for all places in the US. You can loop over that by date and filter down to just the schools. It returns 500 placekeys at a time, and you can feed in the most recently returned placekey to paginate through the dataset. It'll be a lot of data, but it's the quickest way using our API at the moment to get large amounts of data.  

cc @MTaylor24 

```
query AcademicBulkWeeklyPatterns(
  $date: DateTime!
  $iso_country_code: String
  $last_seen_placekey: String
) {
  bulk_weekly_patterns(
    date: $date
    iso_country_code: $iso_country_code
    last_seen_placekey: $last_seen_placekey
  ) {
    placekey
    parent_placekey
    location_name
    street_address
    city
    region
    postal_code
    iso_country_code
    safegraph_brand_ids
    brands
    date_range_start
    date_range_end
    raw_visit_counts
    raw_visitor_counts
    visits_by_day
    visits_by_each_hour
    poi_cbg
    visitor_home_cbgs 
    visitor_home_aggregation 
    visitor_daytime_cbgs 
    visitor_country_of_origin 
    distance_from_home
    median_dwell
    bucketed_dwell_times 
    related_same_day_brand 
    related_same_week_brand
    device_type
  }
}
```

**Comment by aghalandar** [comment]
Hey @e-chong
Thank you for the response. I know! it is a lot. I prefer it mass-download the data from the shop and apparently, the weekly pattern is not available. 

thank you for the solution. I want to run the new code; However, when I  start the code again, after 
sgql_client = sgql.HTTP_Client(apikey) 
I still get the following error: 

HTTPError: 429 Client Error: Too Many Requests for url: https://api.safegraph.com/v1/graphql

I also get a new API key, but I get the same error.

**Comment by echong-SG** [comment]
Hey @aghalandar ah, we have a rate limit on for users right now as we're working through beta.

Can you email your apikey and the email address you used to register to `eugene at safegraph dot com`? I will get you whitelisted.

**Comment by aghalandar** [comment]
I add to your code the following as queri variable : 
{ "date": "2021-07-26",
  "iso_country_code": "US",
  "last_seen_placekey": "zzw-225@5sb-86x-vs5"
}

When I run the code, I get the following error: 

{
  "errors": [
    {
      "message": "Cannot query field 'bulk_weekly_patterns' on type 'Query'. Did you mean 'supplemental_patterns'? (line 7, column 3):\n{ bulk_weekly_patterns(\n  ^",
      "locations": [
        {
          "line": 7,
          "column": 3
        }
      ]
    }
  ]
}

**Comment by echong-SG** [comment]
@aghalandar can you post the exact full query that you tried to use?

**Comment by echong-SG** [comment]
sorry @aghalandar , I see the issue. I forgot to mention in my first message that that Query type uses a different endpoint.  Please use `https://placesapi.safegraph.com/v1/graphql/bulk` instead of `https://placesapi.safegraph.com/v1/graphql/`.

**Comment by aghalandar** [comment]
Now, I change the endpoint. My code is as follows: 
from sgqlc.endpoint.http import HTTPEndpoint

url = 'https://placesapi.safegraph.com/v1/graphql/bulk'
headers = {'Authorization': ' my tocken here'}

endpoint = HTTPEndpoint(url, headers)

query = '''query {
  lookup(placekey: "222-224@5vg-7gr-6kz") {
    placekey
    safegraph_core {
      location_name
      street_address
      city
      region
      postal_code
      iso_country_code
    }
  }
}'''


data = endpoint(query)

I just want to check a simple query and I get the error: 
https://placesapi.safegraph.com/v1/graphql/bulk: HTTP Error 401: Unauthorized

I also cannot use the SafegraphQl anymore since I have to change the endpoint. I am not sure how I can change the endpoint in safegraphQL.

**Comment by echong-SG** [comment]
Hey @aghalandar, sorry for the confusion here.

The "bulk" endpoint works _only_ with the `AcademicBulkWeeklyPatterns` query type shown below, and it is _not_ supported by the safegraphQL library. In short, this is b/c `AcademicBulkWeeklyPatterns` is a temporary solution we created to support bulk queries like the one you're trying to do while we fix up some things on the backend that will let us support those queries on the regular endpoint.

The `gql` library is what we built the safegraphQL library on top of, and that might be helpful for you constructing this query: https://github.com/graphql-python/gql

I'll also ask some of our other academic community members who've been using this endpoint if they have some code to share that would be helpful for you.

Appreciate your patience here.


```
query AcademicBulkWeeklyPatterns(
  $date: DateTime!
  $iso_country_code: String
  $last_seen_placekey: String
) {
  bulk_weekly_patterns(
    date: $date
    iso_country_code: $iso_country_code
    last_seen_placekey: $last_seen_placekey
  ) {
    placekey
    parent_placekey
    location_name
    street_address
    city
    region
    postal_code
    iso_country_code
    safegraph_brand_ids
    brands
    date_range_start
    date_range_end
    raw_visit_counts
    raw_visitor_counts
    visits_by_day
    visits_by_each_hour
    poi_cbg
    visitor_home_cbgs 
    visitor_home_aggregation 
    visitor_daytime_cbgs 
    visitor_country_of_origin 
    distance_from_home
    median_dwell
    bucketed_dwell_times 
    related_same_day_brand 
    related_same_week_brand
    device_type
  }
}
```

**Comment by aghalandar** [comment]
Thank you for your help and support. That would be great. 
I am not very advance in python.

**Comment by echong-SG** [comment]
@aghalandar are you comfortable using curl? The below should work - you just need to update the `date` and `last_seen_placekey` and change `YOUR_API_KEY` to loop through the data.

```
curl 'https://api.safegraph.com/v1/graphql/bulk' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://places-api.safegraph.io' -H 'apikey: YOUR_API_KEY' --data-binary '{"query":"query AcademicBulkWeeklyPatterns(\n  $date: DateTime!\n  $iso_country_code: String\n  $last_seen_placekey: String\n) {\n  bulk_weekly_patterns(\n    date: $date\n    iso_country_code: $iso_country_code\n    last_seen_placekey: $last_seen_placekey\n  ) {\n    placekey\n    parent_placekey\n    location_name\n    street_address\n    city\n    region\n    postal_code\n    iso_country_code\n    safegraph_brand_ids\n    brands\n    date_range_start\n    date_range_end\n    raw_visit_counts\n    raw_visitor_counts\n    visits_by_day\n    visits_by_each_hour\n    poi_cbg\n    visitor_home_cbgs \n    visitor_home_aggregation \n    visitor_daytime_cbgs \n    visitor_country_of_origin \n    distance_from_home\n    median_dwell\n    bucketed_dwell_times \n    related_same_day_brand \n    related_same_week_brand\n    device_type\n  }\n}","variables":{"date":"2021-09-20","iso_country_code":"US","last_seen_placekey":""}}' --compressed
```

**Comment by aghalandar** [comment]
That works great. Now I can download the data. 
For the final questions. Does it matter which API I use as the first one for "last_seen_placekey"? Or, it does not matter?
I understand there would be many requests. does it cause any problem from the server side? I just want to download responsibly.

**Comment by echong-SG** [comment]
For `last_seen_placekey`, I believe what you need to do is set that as empty for the very first query, which will return 500 rows, and then you should use the very last placekey returned to get another set of 500, etc. Does that answer your question?

And no limits on this bulk_weekly_patterns query type. We made this bulk endpoint specifically for users like you who wanted to download lots of data 🙂

**Comment by mirkan1** [comment]
```
from time import sleep
for i in placekeys:
   sgql_client.lookup(i)
   sleep(.33)
   sgql_client.save(i+".csv")
```

try it with caution
